included:
  - ColimaSwift

excluded:
  - build
  - .build

line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true

identifier_name:
  min_length: 2
  excluded:
    - id

type_name:
  min_length: 3

function_body_length:
  warning: 80
  error: 150

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 600
  error: 1000

disabled_rules:
  - todo
  - trailing_comma

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - contains_over_first_not_nil
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unused_import
  - vertical_parameter_alignment_on_call
  - yoda_condition

reporter: xcode
